using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Ason.Tests.Operators;

/// <summary>
/// Pins the text the Script agent receives as its operator API (the <c>&lt;api&gt;</c> block of the script
/// prompt). That text is generated by <see cref="ProxySerializer"/> and is a contract: if the async plumbing
/// leaks back in, a type stops being unwrapped or a description disappears, generated scripts start failing
/// while every other test stays green. These assertions are the only guard on that contract.
///
/// Note the renderings the assertions pin: types use CLR names (<c>Int32</c>, <c>String</c>) rather than C#
/// keywords, which is what the presets have always contained. Switching to keywords changes the prompt the
/// model sees, so it must be a deliberate change that shows up here.
/// </summary>
public class OperatorSignatureTextTests {

    static string Signatures => ProxySerializer.SerializeSignatures(typeof(OperatorSignatureTextTests).Assembly);

    [Fact]
    public void Async_methods_lose_the_suffix_and_the_task_wrapper() {
        Assert.Contains("public Int32 Sum(Int32 a, Int32 b);", Signatures);   // async Task<int> SumAsync(int, int)
        Assert.Contains("public Int32 Add(Int32 a, Int32 b);", Signatures);   // async Task<int> AddAsync(int, int)
        Assert.Contains("public String Concat(String a, String b);", Signatures);

        Assert.DoesNotContain("SumAsync", Signatures);
        Assert.DoesNotContain("AddAsync", Signatures);
        Assert.DoesNotContain("ConcatAsync", Signatures);
    }

    [Fact]
    public void No_async_plumbing_reaches_the_agent() {
        // The whole point of the generated surface: the model never sees Task, await or an Async suffix.
        Assert.DoesNotContain("Task", Signatures);
        Assert.DoesNotContain("Async", Signatures);
    }

    [Fact]
    public void Task_returning_and_void_methods_both_render_as_void() {
        Assert.Contains("public void DoNothing(TestModel model);", Signatures);   // async Task DoNothingAsync(...)
        Assert.Contains("public void Touch();", Signatures);                     // async Task TouchAsync()
        Assert.Contains("public void NoReturnValue();", Signatures);
    }

    [Fact]
    public void Operator_returning_methods_expose_the_operator_type_and_discourage_new() {
        Assert.Contains("public SimpleOp GetSimpleOperator();", Signatures);   // async Task<SimpleOp> where SimpleOp is [AsonOperator]
        Assert.Contains("private SimpleOp();", Signatures);
    }

    [Fact]
    public void Nullable_array_and_generic_shapes_keep_their_form() {
        Assert.Contains("public Int32? MaybeCount(Int32? limit);", Signatures);
        Assert.Contains("public Int32 SumArray(Int32[] numbers);", Signatures);   // array parameter
        Assert.Contains("public List<String> Names();", Signatures);
        Assert.Contains("public Int32? Optional;", Signatures);
        Assert.Contains("public List<Int32> Values;", Signatures);
    }

    [Fact]
    public void Descriptions_from_the_marker_attributes_survive_as_comments() {
        Assert.Contains("// Signature shape operators", Signatures);   // [AsonOperator(description: ...)]
        Assert.Contains("// Counts the items", Signatures);            // [AsonMethod("...")]
        Assert.Contains("// Echoes the text", Signatures);
        Assert.Contains("// Signature shape model", Signatures);       // [AsonModel("...")]
    }

    [Fact]
    public void Static_modules_emit_static_members_in_a_static_class() {
        Assert.Contains("public static class SignatureShapeStatic {", Signatures);
        Assert.Contains("public static String Echo(String text);", Signatures);
    }
}

[AsonOperator(description: "Signature shape operators")]
public class SignatureShapeOp : OperatorBase {
    public SignatureShapeOp() { }

    [AsonMethod("Counts the items")]
    public int Count(int[] values) => values.Length;

    [AsonMethod("May return nothing")]
    public int? MaybeCount(int? limit) => limit;

    [AsonMethod]
    public List<string> Names() => new List<string> { "a" };

    [AsonMethod]
    public async Task<int> SumAsync(int a, int b) { await Task.Yield(); return a + b; }

    [AsonMethod]
    public async Task TouchAsync() => await Task.Yield();
}

[AsonOperator(description: "Static signature shape module")]
public static class SignatureShapeStatic {
    [AsonMethod("Echoes the text")]
    public static string Echo(string text) => text;
}

[AsonModel("Signature shape model")]
public class SignatureShapeModel {
    public string Name { get; set; } = string.Empty;
    public int? Optional { get; set; }
    public List<int> Values { get; set; } = new();
}
