<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>net6.0;net9.0;net10.0</TargetFrameworks>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <BaseOutputPath>..\bin</BaseOutputPath>
	<GeneratePackageOnBuild>true</GeneratePackageOnBuild>
	<IsPackable>true</IsPackable>
	<Authors>Alexgoon</Authors>
	<PackageId>Ason.RemoteBridge</PackageId>
	<Description>Run an ASON environment remotely and connect to it from a client.</Description>
	<RepositoryUrl>https://github.com/Alexgoon/ason</RepositoryUrl>
	<PackageIcon>icon.png</PackageIcon>
  </PropertyGroup>

  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
    <ProjectReference Include="..\Ason.Runner.Core\Ason.Runner.Core.csproj" />
    <ProjectReference Include="..\Ason\Ason.csproj" />
	<None Include="icon.png" Pack="true" PackagePath="\"/>
  </ItemGroup>

</Project>
