<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>net6.0;net9.0</TargetFrameworks>
    <LangVersion>latest</LangVersion>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <GeneratePackageOnBuild>false</GeneratePackageOnBuild>
	<BaseOutputPath>..\bin</BaseOutputPath>
	<GeneratePackageOnBuild>true</GeneratePackageOnBuild>
	<IsPackable>true</IsPackable>
	<Authors>Alexgoon</Authors>
	<PackageId>Ason.Runner.Core</PackageId>
	<Description>A core ASON part responsible for executing generated scripts.</Description>
	<RepositoryUrl>https://github.com/Alexgoon/ason</RepositoryUrl>
	<PackageIcon>icon.png</PackageIcon>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.CodeAnalysis.CSharp.Scripting" Version="4.14.0" />
    <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" Version="8.0.0" />
  </ItemGroup>
  
  <ItemGroup>
    <None Include="icon.png" Pack="true" PackagePath="\"/>
  </ItemGroup>

</Project>
